version: "3"
services:
  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        URL: ${URL}
    restart: always
    ports:
      - 3000:3000
  server:
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile    
    restart: always
    ports:
      - 5001:5001
