version: "3"
services:
  nginx:
    image: nginx
    restart: always
    ports: 
      - "80:80/tcp"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - server
  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile    
    ports:
      - 3000:3000
    restart: always    
  server:
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile    
    restart: always
    ports:
      - 5001:5001
